#!/bin/bash 
git init -qqq
git remote add origin https://github.com/hector1024/docker-magento
git fetch origin -qqq
git checkout origin/main -- compose
mv compose/* ./
mv compose/.gitignore ./
mv compose/.vscode ./
rm -rf compose .git
git init
