#!/bin/bash
git init -qqq
git remote add origin https://release-solutions-admin@bitbucket.org/release-solutions-admin/docker-ecommerce-magento
git fetch origin -qqq
git checkout origin/master -- compose
mv compose/* ./
mv compose/.gitignore ./
mv compose/.vscode ./
rm -rf compose .git
git init
